GET http://localhost:5000

###
POST http://localhost:5000/auth/login
Content-Type: application/json

{
   "login": "CatKitty",
   "password": "123rty78"
}

###
POST http://localhost:5000/auth/signup
Content-Type: application/json

{
   "username": "CatKitty",
   "email": "kitty@litty.com",
   "password": "123rty78"
}

###
DELETE http://localhost:5000/auth/logout

###
GET http://localhost:5000/event/events

###
GET http://localhost:5000/event/running

###
GET http://localhost:5000/match/matches
Content-Type: application/json

{
   "ids": ["6016eb3cab5762fee7e18e65", "6016eb3cab5762fee7e18e63"]
}

###
GET http://localhost:5000/match/match
Content-Type: application/json

{
   "id": "6016eb3cab5762fee7e18e65"
}
###
GET http://localhost:5000/team/teams

###
GET http://localhost:5000/team/verified

###
GET http://localhost:5000/team/team?teamName=Gamer Boys

###
GET http://localhost:5000/team/team?id=6016e9a5ab5762fee7e18e59

###
GET http://localhost:5000/event/verified?page=1&numfetched=10

###
GET http://localhost:5000/event/featured?page=1&numfetched=10

###
GET http://localhost:5000/event/unverified?page=1&numfetched=10

###
GET http://localhost:5000/match/match?id=6016eb3cab5762fee7e18e65

###
GET http://localhost:5000/event/event?id=6016efe0ab5762fee7e18e70

###
GET http://localhost:5000/player/player?id=6016e4b4ab5762fee7e18e4b

###
POST http://localhost:5000/team/newTeam
Content-Type: application/json

{
   
}

###
PATCH  http://localhost:5000/event/newEvent?id=606b57bf2cc078f5b7adb184
Content-Type: application/json

{
   "runningStatus": true,
   "dateCreated": "2021-04-14T02:51:50.369+00:00",
   "startDate": "2021-05-01T05:00:00.000+00:00",
   "endDate": "",
   "watchLink" : "",
   "verified" : true,
   "featured": true,
   "brackets" : [{
        "BracketName": "Bracket 87",
        "PushPerMatch": true,
        "PushWinner": 1,
        "PushLoser": 1,
        "matches": [{
           "match":{
               "teams": [{
               "id": "6016e68aab5762fee7e18e51",
               "name": "Gamer Boys",
               "activeStatus": true
           },
           {
               "id": "6016e9a5ab5762fee7e18e59",
               "name": "Faze Clan",
               "activeStatus": true
           }
           ],
           "score": [11,5],
           "winner": 1,
            "loser": 2,
            "winsNeeded": 4,
            "activeStatus": true,
            "timePlayed": "2021-04-01T04:00:00.000+00:00"
           },
           "prize": "$90000"
        },
        {"match":{
               "teams": [{
               "id": "6016e68aab5762fee7e18e56",
               "name": "Wonder Gamers",
               "activeStatus": true
           },
           {
               "id": "6016e9a5ab5759fee7e18e59",
               "name": "Wizkids",
               "activeStatus": true
           }
           ],
           "score": [9,0],
           "winner": 1,
            "loser": 2,
            "winsNeeded": 5,
            "activeStatus": true,
            "timePlayed": "2021-04-01T04:00:00.000+00:00"
           },
           "prize": "$110000"
        }
        ]
   }],
   "teams": [{
               "id": "6016e68aab5762fee7e18e51",
               "name": "Gamer Boys",
               "activeStatus": true
           },
           {
               "id": "6016e9a5ab5762fee7e18e59",
               "name": "Faze Clan",
               "activeStatus": true
           },
           {
               "id": "6016e68aab5762fee7e18e56",
               "name": "Wonder Gamers",
               "activeStatus": true
           },
           {
               "id": "6016e9a5ab5759fee7e18e59",
               "name": "Wizkids",
               "activeStatus": true
           }
           ],
   "name": "V-R Updated Event"
}

###
POST http://localhost:5000/player/newPlayer
Content-Type: application/json

{
   
}
